[2024-02-22T13:19:37.827+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-02-22T13:19:34.859865+00:00 [queued]>
[2024-02-22T13:19:37.838+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-02-22T13:19:34.859865+00:00 [queued]>
[2024-02-22T13:19:37.839+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-22T13:19:37.855+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-02-22 13:19:34.859865+00:00
[2024-02-22T13:19:37.865+0000] {standard_task_runner.py:60} INFO - Started process 53 to run task
[2024-02-22T13:19:37.869+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-02-22T13:19:34.859865+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp5pthjts5']
[2024-02-22T13:19:37.871+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask reddit_extraction
[2024-02-22T13:19:37.931+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-02-22T13:19:34.859865+00:00 [running]> on host 7ef89de276e5
[2024-02-22T13:19:38.024+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ACHRAF ZHAR' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-02-22T13:19:34.859865+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-22T13:19:34.859865+00:00'
[2024-02-22T13:19:38.374+0000] {logging_mixin.py:188} INFO - Connected to reddit !
[2024-02-22T13:19:43.316+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 7, in reddit_pipeline
    posts = extract_posts(instance, subreddit, time_filter, limit)
  File "/opt/airflow/etls/reddit_etl.py", line 31, in extract_posts
    retrieved_count += len(posts)
TypeError: object of type 'ListingGenerator' has no len()
[2024-02-22T13:19:43.334+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, execution_date=20240222T131934, start_date=20240222T131937, end_date=20240222T131943
[2024-02-22T13:19:43.356+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2 for task reddit_extraction (object of type 'ListingGenerator' has no len(); 53)
[2024-02-22T13:19:43.376+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-22T13:19:43.407+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
